# Convert the CSV Data to RDF

## Create Deep JSON

In the following part, all informations from the different CSV files are combined into a single JSON structure. This is done by iterating over the rows of the `party_csv` and fetching all the related information from the other CSV files.

In [19]:
import pandas as pd

party_csv = pd.read_csv("../data/input/party.csv")
party_name_csv = pd.read_csv("../data/input/party_name.csv")
relationship_csv = pd.read_csv("../data/input/relationship.csv")
relationship_type_csv = pd.read_csv("../data/input/relationship_type.csv")
party_code_csv = pd.read_csv("../data/input/party_code.csv")
party_code_type_csv = pd.read_csv("../data/input/party_code_type.csv")


display(party_csv)

,party_id,identifier,color,party_name_id,relationship_id_1,relationship_id_2,social_group_id,party_category_id,election_result_id,period_of_service_id,...,voting_issue_party_party_id13,voting_issue_notes13,voting_issue_sources13,dissolution_date_precision,dissolution_date_datetime,dissolution_date_notes,dissolution_date_sources,translations_languages_code3,translations_description3,translations_hls_link_external_url3
0,1,svp-ch,#4B8A3E,[1],"[3,9]","[5,12,35,69,90,98,141,174,192,193,232,260,276,...",[1],[16],"[1,2,3,4,5,6,7,8,9,10,11,12,13,14,106,107,108,...","[1,2,3,4,5,6,7,8,9,562,563,564,565,566,567,568...",...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,sp-ch,#F0554D,[2],[],"[13,36,70,91,99,142,175,196,201,202,233,234,26...",[2],[1],"[15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,...","[10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,fdplib-ch,#3B79BF,[3],"[1,6]","[18,38,72,93,101,135,144,177,203,205,210,240,2...",[3],[15],"[43,44,45,46,148,149,150,151,6290,7226,7227,72...","[38,39,40,41]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,mitte-ch,#D6862B,[4],"[2,4]","[21,31,40,43,61,75,95,103,125,145,146,163,180,...",[4],[14],"[47,152,6284,7250,7251,7252,7253]","[42,43,611,612]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,gruene-ch,#84B547,"[6,7,8,9,199]",[],"[22,44,45,48,49,53,54,56,78,79,96,104,105,106,...",[5],[13],"[48,49,50,51,52,53,54,55,56,57,58,59,60,153,15...","[44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,308,pda-sg-1,NaN,[494],[456],[457],[304],[301],"[9623,9624,9625,9761,9762,9763,9970,9971,10122...",[],...,NaN,NaN,NaN,multiyear,1985-01-01T12:00:00,NaN,page_number_string: \r\nnotes: \r\nsource_full...,NaN,NaN,NaN
304,309,pda-sg-2,NaN,[495],"[457,458]",[],[305],[302],[],[],...,NaN,NaN,NaN,unknown,2020-01-01T12:00:00,NaN,NaN,NaN,NaN,NaN
305,310,ap-sg,NaN,[496],[],[],[306],[303],"[9626,9627,9628,9629,9764,9765,9766,9767,9972,...",[],...,NaN,NaN,NaN,month,2000-01-15T12:00:00,NaN,page_number_string: \r\nnotes: \r\nsource_full...,NaN,NaN,NaN
306,311,bdp-gr,NaN,"[497,498,499,500]","[459,460,461]",[463],[307],[304],[],[],...,NaN,NaN,NaN,exact,2021-06-07T12:00:00,NaN,page_number_string: \r\nnotes: \r\nsource_full...,NaN,NaN,NaN
307,312,svp-gr,NaN,[501],"[462,463]",[],[308],[305],[],[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
display(party_name_csv)

,party_name_id,party_id,notes,sources,translations_languages_code1,translations_abbreviation1,translations_name1,translations_internal_label1,translations_alternative_name1,translations_notes1,...,to_date_datetime,to_date_notes,to_date_sources,translations_languages_code4,translations_abbreviation4,translations_name4,translations_internal_label4,translations_alternative_name4,translations_notes4,translations_sources4
0,1,1,NaN,page_number_string: \r\nnotes: \r\nsource_full...,de-CH,SVP,Schweizerische Volkspartei,SVP,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,NaN,page_number_string: \r\nnotes: \r\nsource_full...,de-CH,SP Schweiz,Sozialdemokratische Partei der Schweiz,SP,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,3,NaN,page_number_string: 5\r\nnotes: \r\nsource_ful...,de-CH,NaN,FDP.Die Liberalen,FDPLIB,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,4,NaN,page_number_string: \r\nnotes: \r\nsource_full...,de-CH,Mitte,Die Mitte,Mitte,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,6,NaN,page_number_string: \r\nnotes: \r\nsource_full...,de-CH,GLP,Grünliberale Partei Schweiz,GLP,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,497,311,NaN,page_number_string: \r\nnotes: \r\nsource_full...,de-CH,NaN,Demokratische Partei Graubündens,Dem. GR,NaN,NaN,...,1971-07-01T12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
491,498,311,NaN,page_number_string: \r\nnotes: \r\nsource_full...,de-CH,SVP Graubünden,Schweizerische Volkspartei Graubünden,SVP GR,NaN,NaN,...,2008-06-16T12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
492,499,311,NaN,page_number_string: \r\nnotes: \r\nsource_full...,de-CH,BPS Graubünden,Bürgerliche Partei Schweiz Graubünden,BPS GR,NaN,NaN,...,2008-07-02T12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,500,311,NaN,page_number_string: \r\nnotes: \r\nsource_full...,de-CH,BDP Graubünden,Bürgerlich - Demokratische Partei Kanton Grau...,BDP GR,NaN,NaN,...,2021-06-06T12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,501,312,NaN,page_number_string: \r\nnotes: \r\nsource_full...,de-CH,SVP Graubünden,Schweizerische Volkspartei des Kantons Graubünden,SVP GR,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
def parse_list(s):
    if pd.isna(s) or s == "[]":
        return []
    return [int(item) for item in s.strip("[]").split(",")]

In [38]:
# the following structure should be created:

# parties = {
#    1: {
#         "names": [
#             {"name": "name1", "from_date": "date1", "to_date": "date2"},
#             {"name": "name2", "from_date": "date3", "to_date": "date4"},
#         ],
#         "relationships": [...],
#     },
#     2: {
#         "names": [...],
#         "relationships": [...],
#     },
#     ...
# ]

parties = {}

for _, row in party_csv.iterrows():
    
    party = {}
    
    party_id = row["party_id"]
    
    # get party names
    party_name_ids = parse_list(row["party_name_id"])

    names = []

    for party_name_id in party_name_ids:
        name_lang = {}
        for lang_id in range(1, 5):  # there are 4 language columns (1, 2, 3, 4)
            lang_abbr = party_name_csv.loc[party_name_csv["party_name_id"] == party_name_id, f"translations_languages_code{lang_id}"].item()
            name = party_name_csv.loc[party_name_csv["party_name_id"] == party_name_id, f"translations_name{lang_id}"].item()
            if str(lang_abbr) != "nan" and str(name) != "nan":
                name_lang[str(lang_abbr)[0:2]] = name
        abbr_lang = {}
        for lang_id in range(1, 5):  # there are 4 language columns (1, 2, 3, 4)
            lang_abbr = party_name_csv.loc[party_name_csv["party_name_id"] == party_name_id, f"translations_languages_code{lang_id}"].item()
            abbr = party_name_csv.loc[party_name_csv["party_name_id"] == party_name_id, f"translations_abbreviation{lang_id}"].item()
            if str(lang_abbr) != "nan" and str(abbr) != "nan":
                abbr_lang[str(lang_abbr)[0:2]] = abbr
        from_date = party_name_csv.loc[party_name_csv["party_name_id"] == party_name_id, "from_date_datetime"].item()
        to_date = party_name_csv.loc[party_name_csv["party_name_id"] == party_name_id, "to_date_datetime"].item()
        name_entry = {"id": party_name_id, "name": name_lang, "abbr": abbr_lang, "from_date": from_date, "to_date": to_date}
        names.append(name_entry)

    
    # sort by from_date
    names.sort(key=lambda x: x["from_date"])
    party["names"] = names


    # get relationships, they are given in two columns, relationship_id_1 and relationship_id_2.
    # all child-of relationships go to `child_relationships`, all other relationships go to `relationships`.
    # maybe I'm missing out on some meaning of the two columns, but for now I will just combine them and sort by from_date.
    relationships_1 = []
    relationships_2 = []

    # get relationships_1
    relationship_ids_1 = parse_list(row["relationship_id_1"])

    for relationship_id in relationship_ids_1:
        relationship_to = relationship_csv.loc[relationship_csv["relationship_id"] == relationship_id, "party_2_id"].item()
        relationship_type = relationship_csv.loc[relationship_csv["relationship_id"] == relationship_id, "type"].item()
        relationship_label = relationship_type_csv.loc[relationship_type_csv["relationship_type_id"] == relationship_type, "identifier"].item()
        date_from = relationship_csv.loc[relationship_csv["relationship_id"] == relationship_id, "from_date_datetime"].item()
        date_to = relationship_csv.loc[relationship_csv["relationship_id"] == relationship_id, "to_date_datetime"].item()
        relationship_entry = {"id": relationship_id, "type_label": relationship_label, "party": relationship_to, "from_date": date_from, "to_date": date_to}
        if relationship_entry["type_label"] != "child-of":
            relationships_1.append(relationship_entry)
        else:
            relationships_2.append(relationship_entry)

    # get relationships_2
    relationship_ids_2 = parse_list(row["relationship_id_2"])


    for relationship_id in relationship_ids_2:
        relationship_from = relationship_csv.loc[relationship_csv["relationship_id"] == relationship_id, "party_1_id"].item()
        relationship_type = relationship_csv.loc[relationship_csv["relationship_id"] == relationship_id, "type"].item()
        relationship_label = relationship_type_csv.loc[relationship_type_csv["relationship_type_id"] == relationship_type, "identifier"].item()
        date_from = relationship_csv.loc[relationship_csv["relationship_id"] == relationship_id, "from_date_datetime"].item()
        date_to = relationship_csv.loc[relationship_csv["relationship_id"] == relationship_id, "to_date_datetime"].item()
        relationship_entry = {"id": relationship_id, "type_label": relationship_label, "party": relationship_from, "from_date": date_from, "to_date": date_to}
        if relationship_entry["type_label"] != "child-of":
            relationships_1.append(relationship_entry)
        else:
            relationships_2.append(relationship_entry)

    # sort relationships by from_date and add them to the party dictionary
    relationships_1.sort(key=lambda x: x["from_date"])
    relationships_2.sort(key=lambda x: x["from_date"])
    party["relationships"] = relationships_1
    party["child_relationships"] = relationships_2

    # different identifiers for the same party (e.g. bfs-code, wikidata, etc.)
    party_code_ids = parse_list(row["party_code_id"])
    party_codes = []

    for party_code_id in party_code_ids:
        code = party_code_csv.loc[party_code_csv["party_code_id"] == party_code_id, "code"].item()
        code_type = party_code_csv.loc[party_code_csv["party_code_id"] == party_code_id, "party_code_type_id"].item()
        code_type_label = party_code_type_csv.loc[party_code_type_csv["party_code_type_id"] == code_type, "identifier"].item()

        code_entry = {"id": party_code_id, "code": code, "type_label": code_type_label}
        party_codes.append(code_entry)

    party_codes.append({"code": row["identifier"], "type_label": "ap-identifier"})  # add the identifier from the party.csv row

    party["party_codes"] = party_codes


    # add party to parties dictionary (finish line operations)
    parties[party_id] = party

In [39]:
import json

print(json.dumps(parties, indent=2, ensure_ascii=False))

{
  "1": {
    "names": [
      {
        "id": 1,
        "name": {
          "de": "Schweizerische Volkspartei",
          "fr": "Union Démocratique du Centre",
          "en": "Schweizerische Volkspartei"
        },
        "abbr": {
          "de": "SVP",
          "fr": "UDC"
        },
        "from_date": "1971-09-22T12:00:00",
        "to_date": NaN
      }
    ],
    "relationships": [
      {
        "id": 3,
        "type_label": "successor-of",
        "party": 11,
        "from_date": "1971-09-22T12:00:00",
        "to_date": NaN
      },
      {
        "id": 9,
        "type_label": "successor-of",
        "party": 18,
        "from_date": "1971-09-22T12:00:00",
        "to_date": NaN
      },
      {
        "id": 5,
        "type_label": "split-from",
        "party": 13,
        "from_date": "2008-11-01T12:00:00",
        "to_date": NaN
      }
    ],
    "child_relationships": [
      {
        "id": 12,
        "type_label": "child-of",
        "party": 20,
        "from_date": "1971-09-22T12:00:00",
        "to_date": NaN
      },
      {
        "id": 35,
        "type_label": "child-of",
        "party": 35,
        "from_date": "1971-09-22T12:00:00",
        "to_date": NaN
      },
      {
        "id": 141,
        "type_label": "child-of",
        "party": 103,
        "from_date": "1971-09-22T12:00:00",
        "to_date": NaN
      },
      {
        "id": 232,
        "type_label": "child-of",
        "party": 161,
        "from_date": "1971-09-22T12:00:00",
        "to_date": NaN
      },
      {
        "id": 302,
        "type_label": "child-of",
        "party": 210,
        "from_date": "1971-09-22T12:00:00",
        "to_date": NaN
      },
      {
        "id": 336,
        "type_label": "child-of",
        "party": 231,
        "from_date": "1971-09-22T12:00:00",
        "to_date": NaN
      },
      {
        "id": 397,
        "type_label": "child-of",
        "party": 265,
        "from_date": "1971-09-22T12:00:00",
        "to_date": NaN
      },
      {
        "id": 460,
        "type_label": "child-of",
        "party": 311,
        "from_date": "1971-09-22T12:00:00",
        "to_date": "2008-06-16T12:00:00"
      },
      {
        "id": 260,
        "type_label": "child-of",
        "party": 181,
        "from_date": "1975-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 420,
        "type_label": "child-of",
        "party": 280,
        "from_date": "1975-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 174,
        "type_label": "child-of",
        "party": 123,
        "from_date": "1979-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 371,
        "type_label": "child-of",
        "party": 249,
        "from_date": "1991-06-20T12:00:00",
        "to_date": NaN
      },
      {
        "id": 98,
        "type_label": "child-of",
        "party": 74,
        "from_date": "1991-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 319,
        "type_label": "child-of",
        "party": 221,
        "from_date": "1991-09-11T12:00:00",
        "to_date": NaN
      },
      {
        "id": 69,
        "type_label": "child-of",
        "party": 54,
        "from_date": "1992-04-30T12:00:00",
        "to_date": NaN
      },
      {
        "id": 441,
        "type_label": "child-of",
        "party": 298,
        "from_date": "1992-11-23T12:00:00",
        "to_date": NaN
      },
      {
        "id": 431,
        "type_label": "child-of",
        "party": 287,
        "from_date": "1996-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 90,
        "type_label": "child-of",
        "party": 67,
        "from_date": "1998-12-05T12:00:00",
        "to_date": NaN
      },
      {
        "id": 192,
        "type_label": "child-of",
        "party": 139,
        "from_date": "1999-07-15T12:00:00",
        "to_date": NaN
      },
      {
        "id": 287,
        "type_label": "child-of",
        "party": 201,
        "from_date": "1999-08-28T12:00:00",
        "to_date": NaN
      },
      {
        "id": 276,
        "type_label": "child-of",
        "party": 192,
        "from_date": "1999-12-03T12:00:00",
        "to_date": NaN
      },
      {
        "id": 193,
        "type_label": "child-of",
        "party": 140,
        "from_date": "2002-09-27T12:00:00",
        "to_date": NaN
      },
      {
        "id": 462,
        "type_label": "child-of",
        "party": 312,
        "from_date": "2008-06-19T12:00:00",
        "to_date": NaN
      }
    ],
    "party_codes": [
      {
        "id": 1,
        "code": "220",
        "type_label": "obelis-code"
      },
      {
        "id": 2,
        "code": "4",
        "type_label": "bfs-code"
      },
      {
        "id": 17,
        "code": "Q385258",
        "type_label": "wikidata-code"
      },
      {
        "code": "svp-ch",
        "type_label": "ap-identifier"
      }
    ]
  },
  "2": {
    "names": [
      {
        "id": 2,
        "name": {
          "de": "Sozialdemokratische Partei der Schweiz",
          "fr": "Parti socialiste suisse"
        },
        "abbr": {
          "de": "SP Schweiz",
          "fr": "PS Suisse"
        },
        "from_date": "1888-10-21T12:00:00",
        "to_date": NaN
      }
    ],
    "relationships": [
      {
        "id": 368,
        "type_label": "affiliated-with",
        "party": 248,
        "from_date": "1901-07-01T12:00:00",
        "to_date": "1906-07-01T12:00:00"
      },
      {
        "id": 369,
        "type_label": "accessed",
        "party": 248,
        "from_date": "1925-07-01T12:00:00",
        "to_date": NaN
      }
    ],
    "child_relationships": [
      {
        "id": 99,
        "type_label": "child-of",
        "party": 75,
        "from_date": "1890-06-26T12:00:00",
        "to_date": NaN
      },
      {
        "id": 70,
        "type_label": "child-of",
        "party": 55,
        "from_date": "1895-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 374,
        "type_label": "child-of",
        "party": 251,
        "from_date": "1897-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 317,
        "type_label": "child-of",
        "party": 220,
        "from_date": "1900-01-01T12:00:00",
        "to_date": "1917-07-01T12:00:00"
      },
      {
        "id": 233,
        "type_label": "child-of",
        "party": 163,
        "from_date": "1900-07-01T12:00:00",
        "to_date": "1992-10-18T12:00:00"
      },
      {
        "id": 13,
        "type_label": "child-of",
        "party": 21,
        "from_date": "1902-04-13T12:00:00",
        "to_date": NaN
      },
      {
        "id": 338,
        "type_label": "child-of",
        "party": 222,
        "from_date": "1902-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 36,
        "type_label": "child-of",
        "party": 36,
        "from_date": "1905-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 442,
        "type_label": "child-of",
        "party": 299,
        "from_date": "1905-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 337,
        "type_label": "child-of",
        "party": 232,
        "from_date": "1908-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 91,
        "type_label": "child-of",
        "party": 68,
        "from_date": "1909-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 401,
        "type_label": "child-of",
        "party": 268,
        "from_date": "1911-07-01T12:00:00",
        "to_date": "1921-07-01T12:00:00"
      },
      {
        "id": 142,
        "type_label": "child-of",
        "party": 104,
        "from_date": "1913-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 421,
        "type_label": "child-of",
        "party": 281,
        "from_date": "1913-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 303,
        "type_label": "child-of",
        "party": 211,
        "from_date": "1917-12-30T12:00:00",
        "to_date": NaN
      },
      {
        "id": 261,
        "type_label": "child-of",
        "party": 182,
        "from_date": "1919-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 201,
        "type_label": "child-of",
        "party": 141,
        "from_date": "1919-12-07T12:00:00",
        "to_date": "1982-05-01T12:00:00"
      },
      {
        "id": 400,
        "type_label": "child-of",
        "party": 266,
        "from_date": "1935-07-07T12:00:00",
        "to_date": NaN
      },
      {
        "id": 288,
        "type_label": "child-of",
        "party": 202,
        "from_date": "1942-07-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 196,
        "type_label": "child-of",
        "party": 143,
        "from_date": "1982-05-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 202,
        "type_label": "child-of",
        "party": 144,
        "from_date": "1982-05-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 175,
        "type_label": "child-of",
        "party": 124,
        "from_date": "1983-03-25T12:00:00",
        "to_date": NaN
      },
      {
        "id": 234,
        "type_label": "child-of",
        "party": 164,
        "from_date": "1992-10-18T12:00:00",
        "to_date": NaN
      },
      {
        "id": 277,
        "type_label": "child-of",
        "party": 193,
        "from_date": "1998-02-02T12:00:00",
        "to_date": NaN
      },
      {
        "id": 434,
        "type_label": "child-of",
        "party": 292,
        "from_date": "2012-08-17T12:00:00",
        "to_date": NaN
      }
    ],
    "party_codes": [
      {
        "id": 3,
        "code": "3",
        "type_label": "bfs-code"
      },
      {
        "id": 4,
        "code": "750",
        "type_label": "obelis-code"
      },
      {
        "id": 16,
        "code": "Q303745",
        "type_label": "wikidata-code"
      },
      {
        "code": "sp-ch",
        "type_label": "ap-identifier"
      }
    ]
  },
  "3": {
    "names": [
      {
        "id": 3,
        "name": {
          "de": "FDP.Die Liberalen",
          "fr": "PLR.Les Libéraux-Radicaux"
        },
        "abbr": {},
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      }
    ],
    "relationships": [
      {
        "id": 1,
        "type_label": "successor-of",
        "party": 9,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 6,
        "type_label": "successor-of",
        "party": 15,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      }
    ],
    "child_relationships": [
      {
        "id": 18,
        "type_label": "child-of",
        "party": 24,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 38,
        "type_label": "child-of",
        "party": 37,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 72,
        "type_label": "child-of",
        "party": 56,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 93,
        "type_label": "child-of",
        "party": 69,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 101,
        "type_label": "child-of",
        "party": 76,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 135,
        "type_label": "child-of",
        "party": 92,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 144,
        "type_label": "child-of",
        "party": 105,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 177,
        "type_label": "child-of",
        "party": 125,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 205,
        "type_label": "child-of",
        "party": 147,
        "from_date": "2009-01-01T12:00:00",
        "to_date": "2013-09-12T12:00:00"
      },
      {
        "id": 210,
        "type_label": "child-of",
        "party": 149,
        "from_date": "2009-01-01T12:00:00",
        "to_date": "2013-09-12T12:00:00"
      },
      {
        "id": 240,
        "type_label": "child-of",
        "party": 167,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 263,
        "type_label": "child-of",
        "party": 183,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 280,
        "type_label": "child-of",
        "party": 195,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 290,
        "type_label": "child-of",
        "party": 203,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 305,
        "type_label": "child-of",
        "party": 212,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 322,
        "type_label": "child-of",
        "party": 223,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 342,
        "type_label": "child-of",
        "party": 234,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 377,
        "type_label": "child-of",
        "party": 253,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 403,
        "type_label": "child-of",
        "party": 269,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 424,
        "type_label": "child-of",
        "party": 283,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 444,
        "type_label": "child-of",
        "party": 300,
        "from_date": "2009-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 203,
        "type_label": "child-of",
        "party": 145,
        "from_date": "2013-09-12T12:00:00",
        "to_date": NaN
      },
      {
        "id": 435,
        "type_label": "child-of",
        "party": 293,
        "from_date": "2017-06-24T12:00:00",
        "to_date": NaN
      }
    ],
    "party_codes": [
      {
        "id": 5,
        "code": "1",
        "type_label": "bfs-code"
      },
      {
        "id": 11,
        "code": "1916",
        "type_label": "obelis-code"
      },
      {
        "id": 19,
        "code": "Q202638",
        "type_label": "wikidata-code"
      },
      {
        "code": "fdplib-ch",
        "type_label": "ap-identifier"
      }
    ]
  },
  "4": {
    "names": [
      {
        "id": 4,
        "name": {
          "de": "Die Mitte",
          "fr": "Le Centre"
        },
        "abbr": {
          "de": "Mitte"
        },
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      }
    ],
    "relationships": [
      {
        "id": 2,
        "type_label": "successor-of",
        "party": 10,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 4,
        "type_label": "successor-of",
        "party": 13,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      }
    ],
    "child_relationships": [
      {
        "id": 21,
        "type_label": "child-of",
        "party": 25,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 31,
        "type_label": "child-of",
        "party": 31,
        "from_date": "2021-01-01T12:00:00",
        "to_date": "2021-03-27T12:00:00"
      },
      {
        "id": 43,
        "type_label": "child-of",
        "party": 39,
        "from_date": "2021-01-01T12:00:00",
        "to_date": "2021-03-24T12:00:00"
      },
      {
        "id": 61,
        "type_label": "child-of",
        "party": 49,
        "from_date": "2021-01-01T12:00:00",
        "to_date": "2021-03-24T12:00:00"
      },
      {
        "id": 75,
        "type_label": "child-of",
        "party": 57,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 95,
        "type_label": "child-of",
        "party": 70,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 103,
        "type_label": "child-of",
        "party": 77,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 125,
        "type_label": "child-of",
        "party": 102,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 146,
        "type_label": "child-of",
        "party": 107,
        "from_date": "2021-01-01T12:00:00",
        "to_date": "2022-01-01T12:00:00"
      },
      {
        "id": 163,
        "type_label": "child-of",
        "party": 116,
        "from_date": "2021-01-01T12:00:00",
        "to_date": "2022-01-01T12:00:00"
      },
      {
        "id": 180,
        "type_label": "child-of",
        "party": 128,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 213,
        "type_label": "child-of",
        "party": 150,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 217,
        "type_label": "child-of",
        "party": 152,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 219,
        "type_label": "child-of",
        "party": 153,
        "from_date": "2021-01-01T12:00:00",
        "to_date": "2026-02-19T12:00:00"
      },
      {
        "id": 242,
        "type_label": "child-of",
        "party": 168,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 265,
        "type_label": "child-of",
        "party": 184,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 282,
        "type_label": "child-of",
        "party": 196,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 292,
        "type_label": "child-of",
        "party": 204,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 308,
        "type_label": "child-of",
        "party": 214,
        "from_date": "2021-01-01T12:00:00",
        "to_date": "2021-05-12T12:00:00"
      },
      {
        "id": 314,
        "type_label": "child-of",
        "party": 218,
        "from_date": "2021-01-01T12:00:00",
        "to_date": "2021-05-12T12:00:00"
      },
      {
        "id": 324,
        "type_label": "child-of",
        "party": 224,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 346,
        "type_label": "child-of",
        "party": 236,
        "from_date": "2021-01-01T12:00:00",
        "to_date": "2021-07-01T12:00:00"
      },
      {
        "id": 363,
        "type_label": "child-of",
        "party": 245,
        "from_date": "2021-01-01T12:00:00",
        "to_date": "2021-07-01T12:00:00"
      },
      {
        "id": 379,
        "type_label": "child-of",
        "party": 254,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 406,
        "type_label": "child-of",
        "party": 270,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 427,
        "type_label": "child-of",
        "party": 284,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {
        "id": 437,
        "type_label": "child-of",
        "party": 294,
        "from_date": "2021-01-01T12:00:00",
        "to_date": NaN
      },
      {

## Convert the Deep JSON to RDF

In [ ]:
from rdflib import Graph, Literal, RDF, URIRef, Namespace

g = Graph()