# Use the RDF Data of the Swiss Political Parties

In [1]:
# load graph from the Turtle file
from rdflib import Graph

g = Graph()
g.parse("../data/output/parties.ttl", format="turtle")

In [2]:
import pandas as pd

def sparql_to_df(graph: Graph, query: str) -> pd.DataFrame:
    result = graph.query(query)
    return pd.DataFrame(
        [
            [val.toPython() if val is not None else None for val in row]
            for row in result
        ],
        columns=[str(var) for var in result.vars]
    )

## Number of Versions per Party

In [3]:
query = """

PREFIX vl: <https://version.link/>

SELECT ?party (COUNT(?version) AS ?count) WHERE {
    ?party a vl:Identity .
    ?version vl:identity ?party .
} GROUP BY ?party ORDER BY DESC(?count)

"""

In [4]:
df = sparql_to_df(g, query)

display(df)

                                         party  count
0      https://politics.ld.admin.ch/party-id/5     18
1    https://politics.ld.admin.ch/party-id/128      9
2    https://politics.ld.admin.ch/party-id/196      6
3    https://politics.ld.admin.ch/party-id/236      6
4     https://politics.ld.admin.ch/party-id/37      6
..                                         ...    ...
300   https://politics.ld.admin.ch/party-id/85      1
301   https://politics.ld.admin.ch/party-id/90      1
302   https://politics.ld.admin.ch/party-id/95      1
303   https://politics.ld.admin.ch/party-id/98      1
304   https://politics.ld.admin.ch/party-id/99      1

[305 rows x 2 columns]

## Party Splits

In [35]:
query = """

PREFIX vl: <https://version.link/>
PREFIX pol: <https://politics.schema.ld.admin.ch/vocab/>


SELECT ?predecessor ?predicate?successor WHERE {

        
    {
        VALUES ?predicate { vl:successor } 

        ?predecessor ?predicate ?successor ;
            pol:splitTo ?another_successor.

    } 
    
    UNION 

    {

        VALUES ?predicate { pol:splitTo } 

        ?predecessor ?predicate ?successor .
    }

}
    
"""

In [36]:
df = sparql_to_df(g, query)

display(df)

,predecessor,predicate,successor
0,https://politics.ld.admin.ch/party-version/104...,https://version.link/successor,https://politics.ld.admin.ch/party-version/104...
1,https://politics.ld.admin.ch/party-version/104...,https://version.link/successor,https://politics.ld.admin.ch/party-version/120...
2,https://politics.ld.admin.ch/party-version/139...,https://version.link/successor,https://politics.ld.admin.ch/party-version/139...
3,https://politics.ld.admin.ch/party-version/139...,https://version.link/successor,https://politics.ld.admin.ch/party-version/140...
4,https://politics.ld.admin.ch/party-version/152...,https://version.link/successor,https://politics.ld.admin.ch/party-version/152...
...,...,...,...
88,https://politics.ld.admin.ch/party-version/75_...,https://politics.schema.ld.admin.ch/vocab/splitTo,https://politics.ld.admin.ch/party-version/98_...
89,https://politics.ld.admin.ch/party-version/88_...,https://politics.schema.ld.admin.ch/vocab/splitTo,https://politics.ld.admin.ch/party-version/89_...
90,https://politics.ld.admin.ch/party-version/57_...,https://politics.schema.ld.admin.ch/vocab/splitTo,https://politics.ld.admin.ch/party-version/62_...
91,https://politics.ld.admin.ch/party-version/1_1...,https://politics.schema.ld.admin.ch/vocab/splitTo,https://politics.ld.admin.ch/party-version/13_...
92,https://politics.ld.admin.ch/party-version/109...,https://politics.schema.ld.admin.ch/vocab/splitTo,https://politics.ld.admin.ch/party-version/108...